// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1ChallengeBackendIDAliensGetOperation        OperationName = "APIV1ChallengeBackendIDAliensGet"
	APIV1ChallengeBackendIDAliensSubmitPostOperation OperationName = "APIV1ChallengeBackendIDAliensSubmitPost"
	APIV1MemberGetOperation                          OperationName = "APIV1MemberGet"
	APIV1MemberRegisterPostOperation                 OperationName = "APIV1MemberRegisterPost"
	GetOperation                                     OperationName = "Get"
	HealthcheckGetOperation                          OperationName = "HealthcheckGet"
)
