// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1RegisterGetOperation OperationName = "APIV1RegisterGet"
	GetOperation              OperationName = "Get"
	HealthcheckGetOperation   OperationName = "HealthcheckGet"
)
