// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1ChallengeIDAliensGetOperation  OperationName = "APIV1ChallengeIDAliensGet"
	APIV1ChallengeIDSubmitPostOperation OperationName = "APIV1ChallengeIDSubmitPost"
	APIV1MemberGetOperation             OperationName = "APIV1MemberGet"
	APIV1MemberRegisterPostOperation    OperationName = "APIV1MemberRegisterPost"
	GetOperation                        OperationName = "Get"
	HealthcheckGetOperation             OperationName = "HealthcheckGet"
)
