// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type APIV1ChallengeIDAliensGetInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1ChallengeIDAliensGetInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1ChallengeIDAliensGetInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*APIV1ChallengeIDAliensGetInternalServerError) aPIV1ChallengeIDAliensGetRes() {}

type APIV1ChallengeIDAliensGetOK struct {
	Waves          []APIV1ChallengeIDAliensGetOKWavesItem       `json:"waves"`
	AlienTypes     OptAPIV1ChallengeIDAliensGetOKAlienTypes     `json:"alienTypes"`
	Budget         OptAPIV1ChallengeIDAliensGetOKBudget         `json:"budget"`
	WallDurability OptAPIV1ChallengeIDAliensGetOKWallDurability `json:"wallDurability"`
}

// GetWaves returns the value of Waves.
func (s *APIV1ChallengeIDAliensGetOK) GetWaves() []APIV1ChallengeIDAliensGetOKWavesItem {
	return s.Waves
}

// GetAlienTypes returns the value of AlienTypes.
func (s *APIV1ChallengeIDAliensGetOK) GetAlienTypes() OptAPIV1ChallengeIDAliensGetOKAlienTypes {
	return s.AlienTypes
}

// GetBudget returns the value of Budget.
func (s *APIV1ChallengeIDAliensGetOK) GetBudget() OptAPIV1ChallengeIDAliensGetOKBudget {
	return s.Budget
}

// GetWallDurability returns the value of WallDurability.
func (s *APIV1ChallengeIDAliensGetOK) GetWallDurability() OptAPIV1ChallengeIDAliensGetOKWallDurability {
	return s.WallDurability
}

// SetWaves sets the value of Waves.
func (s *APIV1ChallengeIDAliensGetOK) SetWaves(val []APIV1ChallengeIDAliensGetOKWavesItem) {
	s.Waves = val
}

// SetAlienTypes sets the value of AlienTypes.
func (s *APIV1ChallengeIDAliensGetOK) SetAlienTypes(val OptAPIV1ChallengeIDAliensGetOKAlienTypes) {
	s.AlienTypes = val
}

// SetBudget sets the value of Budget.
func (s *APIV1ChallengeIDAliensGetOK) SetBudget(val OptAPIV1ChallengeIDAliensGetOKBudget) {
	s.Budget = val
}

// SetWallDurability sets the value of WallDurability.
func (s *APIV1ChallengeIDAliensGetOK) SetWallDurability(val OptAPIV1ChallengeIDAliensGetOKWallDurability) {
	s.WallDurability = val
}

func (*APIV1ChallengeIDAliensGetOK) aPIV1ChallengeIDAliensGetRes() {}

type APIV1ChallengeIDAliensGetOKAlienTypes struct {
	Regular OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular `json:"regular"`
	Swift   OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift   `json:"swift"`
	Boss    OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss    `json:"boss"`
}

// GetRegular returns the value of Regular.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) GetRegular() OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular {
	return s.Regular
}

// GetSwift returns the value of Swift.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) GetSwift() OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift {
	return s.Swift
}

// GetBoss returns the value of Boss.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) GetBoss() OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss {
	return s.Boss
}

// SetRegular sets the value of Regular.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) SetRegular(val OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) {
	s.Regular = val
}

// SetSwift sets the value of Swift.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) SetSwift(val OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) {
	s.Swift = val
}

// SetBoss sets the value of Boss.
func (s *APIV1ChallengeIDAliensGetOKAlienTypes) SetBoss(val OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) {
	s.Boss = val
}

type APIV1ChallengeIDAliensGetOKAlienTypesBoss struct {
	Hp  OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp  `json:"hp"`
	ID  OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID  `json:"id"`
	Atk OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk `json:"atk"`
}

// GetHp returns the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) GetHp() OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp {
	return s.Hp
}

// GetID returns the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) GetID() OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID {
	return s.ID
}

// GetAtk returns the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) GetAtk() OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk {
	return s.Atk
}

// SetHp sets the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) SetHp(val OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) {
	s.Hp = val
}

// SetID sets the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) SetID(val OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) {
	s.ID = val
}

// SetAtk sets the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesBoss) SetAtk(val OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) {
	s.Atk = val
}

type APIV1ChallengeIDAliensGetOKAlienTypesBossAtk int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesBossAtk10 APIV1ChallengeIDAliensGetOKAlienTypesBossAtk = 10
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesBossAtk values.
func (APIV1ChallengeIDAliensGetOKAlienTypesBossAtk) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesBossAtk {
	return []APIV1ChallengeIDAliensGetOKAlienTypesBossAtk{
		APIV1ChallengeIDAliensGetOKAlienTypesBossAtk10,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesBossHp int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesBossHp10 APIV1ChallengeIDAliensGetOKAlienTypesBossHp = 10
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesBossHp values.
func (APIV1ChallengeIDAliensGetOKAlienTypesBossHp) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesBossHp {
	return []APIV1ChallengeIDAliensGetOKAlienTypesBossHp{
		APIV1ChallengeIDAliensGetOKAlienTypesBossHp10,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesBossID int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesBossID3 APIV1ChallengeIDAliensGetOKAlienTypesBossID = 3
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesBossID values.
func (APIV1ChallengeIDAliensGetOKAlienTypesBossID) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesBossID {
	return []APIV1ChallengeIDAliensGetOKAlienTypesBossID{
		APIV1ChallengeIDAliensGetOKAlienTypesBossID3,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesRegular struct {
	Hp  OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp  `json:"hp"`
	ID  OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID  `json:"id"`
	Atk OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk `json:"atk"`
}

// GetHp returns the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) GetHp() OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp {
	return s.Hp
}

// GetID returns the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) GetID() OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID {
	return s.ID
}

// GetAtk returns the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) GetAtk() OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk {
	return s.Atk
}

// SetHp sets the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) SetHp(val OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) {
	s.Hp = val
}

// SetID sets the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) SetID(val OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) {
	s.ID = val
}

// SetAtk sets the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesRegular) SetAtk(val OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) {
	s.Atk = val
}

type APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk3 APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk = 3
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk values.
func (APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk {
	return []APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk{
		APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk3,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesRegularHp int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesRegularHp2 APIV1ChallengeIDAliensGetOKAlienTypesRegularHp = 2
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesRegularHp values.
func (APIV1ChallengeIDAliensGetOKAlienTypesRegularHp) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesRegularHp {
	return []APIV1ChallengeIDAliensGetOKAlienTypesRegularHp{
		APIV1ChallengeIDAliensGetOKAlienTypesRegularHp2,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesRegularID int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesRegularID1 APIV1ChallengeIDAliensGetOKAlienTypesRegularID = 1
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesRegularID values.
func (APIV1ChallengeIDAliensGetOKAlienTypesRegularID) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesRegularID {
	return []APIV1ChallengeIDAliensGetOKAlienTypesRegularID{
		APIV1ChallengeIDAliensGetOKAlienTypesRegularID1,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesSwift struct {
	Hp  OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp  `json:"hp"`
	ID  OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID  `json:"id"`
	Atk OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk `json:"atk"`
}

// GetHp returns the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) GetHp() OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp {
	return s.Hp
}

// GetID returns the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) GetID() OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID {
	return s.ID
}

// GetAtk returns the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) GetAtk() OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk {
	return s.Atk
}

// SetHp sets the value of Hp.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) SetHp(val OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) {
	s.Hp = val
}

// SetID sets the value of ID.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) SetID(val OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) {
	s.ID = val
}

// SetAtk sets the value of Atk.
func (s *APIV1ChallengeIDAliensGetOKAlienTypesSwift) SetAtk(val OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) {
	s.Atk = val
}

type APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk5 APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk = 5
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk values.
func (APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk {
	return []APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk{
		APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk5,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp1 APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp = 1
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp values.
func (APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp {
	return []APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp{
		APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp1,
	}
}

type APIV1ChallengeIDAliensGetOKAlienTypesSwiftID int

const (
	APIV1ChallengeIDAliensGetOKAlienTypesSwiftID2 APIV1ChallengeIDAliensGetOKAlienTypesSwiftID = 2
)

// AllValues returns all APIV1ChallengeIDAliensGetOKAlienTypesSwiftID values.
func (APIV1ChallengeIDAliensGetOKAlienTypesSwiftID) AllValues() []APIV1ChallengeIDAliensGetOKAlienTypesSwiftID {
	return []APIV1ChallengeIDAliensGetOKAlienTypesSwiftID{
		APIV1ChallengeIDAliensGetOKAlienTypesSwiftID2,
	}
}

type APIV1ChallengeIDAliensGetOKBudget int

const (
	APIV1ChallengeIDAliensGetOKBudget100 APIV1ChallengeIDAliensGetOKBudget = 100
)

// AllValues returns all APIV1ChallengeIDAliensGetOKBudget values.
func (APIV1ChallengeIDAliensGetOKBudget) AllValues() []APIV1ChallengeIDAliensGetOKBudget {
	return []APIV1ChallengeIDAliensGetOKBudget{
		APIV1ChallengeIDAliensGetOKBudget100,
	}
}

type APIV1ChallengeIDAliensGetOKWallDurability int

const (
	APIV1ChallengeIDAliensGetOKWallDurability100 APIV1ChallengeIDAliensGetOKWallDurability = 100
)

// AllValues returns all APIV1ChallengeIDAliensGetOKWallDurability values.
func (APIV1ChallengeIDAliensGetOKWallDurability) AllValues() []APIV1ChallengeIDAliensGetOKWallDurability {
	return []APIV1ChallengeIDAliensGetOKWallDurability{
		APIV1ChallengeIDAliensGetOKWallDurability100,
	}
}

type APIV1ChallengeIDAliensGetOKWavesItem struct {
	Aliens []APIV1ChallengeIDAliensGetOKWavesItemAliensItem `json:"aliens"`
}

// GetAliens returns the value of Aliens.
func (s *APIV1ChallengeIDAliensGetOKWavesItem) GetAliens() []APIV1ChallengeIDAliensGetOKWavesItemAliensItem {
	return s.Aliens
}

// SetAliens sets the value of Aliens.
func (s *APIV1ChallengeIDAliensGetOKWavesItem) SetAliens(val []APIV1ChallengeIDAliensGetOKWavesItemAliensItem) {
	s.Aliens = val
}

type APIV1ChallengeIDAliensGetOKWavesItemAliensItem struct {
	Type  APIV1ChallengeIDAliensGetOKWavesItemAliensItemType `json:"type"`
	Count int                                                `json:"count"`
}

// GetType returns the value of Type.
func (s *APIV1ChallengeIDAliensGetOKWavesItemAliensItem) GetType() APIV1ChallengeIDAliensGetOKWavesItemAliensItemType {
	return s.Type
}

// GetCount returns the value of Count.
func (s *APIV1ChallengeIDAliensGetOKWavesItemAliensItem) GetCount() int {
	return s.Count
}

// SetType sets the value of Type.
func (s *APIV1ChallengeIDAliensGetOKWavesItemAliensItem) SetType(val APIV1ChallengeIDAliensGetOKWavesItemAliensItemType) {
	s.Type = val
}

// SetCount sets the value of Count.
func (s *APIV1ChallengeIDAliensGetOKWavesItemAliensItem) SetCount(val int) {
	s.Count = val
}

type APIV1ChallengeIDAliensGetOKWavesItemAliensItemType string

const (
	APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeRegular APIV1ChallengeIDAliensGetOKWavesItemAliensItemType = "regular"
	APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeSwift   APIV1ChallengeIDAliensGetOKWavesItemAliensItemType = "swift"
	APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeBoss    APIV1ChallengeIDAliensGetOKWavesItemAliensItemType = "boss"
)

// AllValues returns all APIV1ChallengeIDAliensGetOKWavesItemAliensItemType values.
func (APIV1ChallengeIDAliensGetOKWavesItemAliensItemType) AllValues() []APIV1ChallengeIDAliensGetOKWavesItemAliensItemType {
	return []APIV1ChallengeIDAliensGetOKWavesItemAliensItemType{
		APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeRegular,
		APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeSwift,
		APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeBoss,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIV1ChallengeIDAliensGetOKWavesItemAliensItemType) MarshalText() ([]byte, error) {
	switch s {
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeRegular:
		return []byte(s), nil
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeSwift:
		return []byte(s), nil
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeBoss:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIV1ChallengeIDAliensGetOKWavesItemAliensItemType) UnmarshalText(data []byte) error {
	switch APIV1ChallengeIDAliensGetOKWavesItemAliensItemType(data) {
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeRegular:
		*s = APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeRegular
		return nil
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeSwift:
		*s = APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeSwift
		return nil
	case APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeBoss:
		*s = APIV1ChallengeIDAliensGetOKWavesItemAliensItemTypeBoss
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIV1ChallengeIDAliensGetUnauthorized struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1ChallengeIDAliensGetUnauthorized) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1ChallengeIDAliensGetUnauthorized) SetMessage(val string) {
	s.Message = val
}

func (*APIV1ChallengeIDAliensGetUnauthorized) aPIV1ChallengeIDAliensGetRes() {}

type APIV1ChallengeIDSubmitPostBadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1ChallengeIDSubmitPostBadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1ChallengeIDSubmitPostBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*APIV1ChallengeIDSubmitPostBadRequest) aPIV1ChallengeIDSubmitPostRes() {}

type APIV1ChallengeIDSubmitPostInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1ChallengeIDSubmitPostInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1ChallengeIDSubmitPostInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*APIV1ChallengeIDSubmitPostInternalServerError) aPIV1ChallengeIDSubmitPostRes() {}

// APIV1ChallengeIDSubmitPostOK represents sum type.
type APIV1ChallengeIDSubmitPostOK struct {
	Type                          APIV1ChallengeIDSubmitPostOKType // switch on this field
	APIV1ChallengeIDSubmitPostOK0 APIV1ChallengeIDSubmitPostOK0
	APIV1ChallengeIDSubmitPostOK1 APIV1ChallengeIDSubmitPostOK1
}

// APIV1ChallengeIDSubmitPostOKType is oneOf type of APIV1ChallengeIDSubmitPostOK.
type APIV1ChallengeIDSubmitPostOKType string

// Possible values for APIV1ChallengeIDSubmitPostOKType.
const (
	APIV1ChallengeIDSubmitPostOK0APIV1ChallengeIDSubmitPostOK APIV1ChallengeIDSubmitPostOKType = "APIV1ChallengeIDSubmitPostOK0"
	APIV1ChallengeIDSubmitPostOK1APIV1ChallengeIDSubmitPostOK APIV1ChallengeIDSubmitPostOKType = "APIV1ChallengeIDSubmitPostOK1"
)

// IsAPIV1ChallengeIDSubmitPostOK0 reports whether APIV1ChallengeIDSubmitPostOK is APIV1ChallengeIDSubmitPostOK0.
func (s APIV1ChallengeIDSubmitPostOK) IsAPIV1ChallengeIDSubmitPostOK0() bool {
	return s.Type == APIV1ChallengeIDSubmitPostOK0APIV1ChallengeIDSubmitPostOK
}

// IsAPIV1ChallengeIDSubmitPostOK1 reports whether APIV1ChallengeIDSubmitPostOK is APIV1ChallengeIDSubmitPostOK1.
func (s APIV1ChallengeIDSubmitPostOK) IsAPIV1ChallengeIDSubmitPostOK1() bool {
	return s.Type == APIV1ChallengeIDSubmitPostOK1APIV1ChallengeIDSubmitPostOK
}

// SetAPIV1ChallengeIDSubmitPostOK0 sets APIV1ChallengeIDSubmitPostOK to APIV1ChallengeIDSubmitPostOK0.
func (s *APIV1ChallengeIDSubmitPostOK) SetAPIV1ChallengeIDSubmitPostOK0(v APIV1ChallengeIDSubmitPostOK0) {
	s.Type = APIV1ChallengeIDSubmitPostOK0APIV1ChallengeIDSubmitPostOK
	s.APIV1ChallengeIDSubmitPostOK0 = v
}

// GetAPIV1ChallengeIDSubmitPostOK0 returns APIV1ChallengeIDSubmitPostOK0 and true boolean if APIV1ChallengeIDSubmitPostOK is APIV1ChallengeIDSubmitPostOK0.
func (s APIV1ChallengeIDSubmitPostOK) GetAPIV1ChallengeIDSubmitPostOK0() (v APIV1ChallengeIDSubmitPostOK0, ok bool) {
	if !s.IsAPIV1ChallengeIDSubmitPostOK0() {
		return v, false
	}
	return s.APIV1ChallengeIDSubmitPostOK0, true
}

// NewAPIV1ChallengeIDSubmitPostOK0APIV1ChallengeIDSubmitPostOK returns new APIV1ChallengeIDSubmitPostOK from APIV1ChallengeIDSubmitPostOK0.
func NewAPIV1ChallengeIDSubmitPostOK0APIV1ChallengeIDSubmitPostOK(v APIV1ChallengeIDSubmitPostOK0) APIV1ChallengeIDSubmitPostOK {
	var s APIV1ChallengeIDSubmitPostOK
	s.SetAPIV1ChallengeIDSubmitPostOK0(v)
	return s
}

// SetAPIV1ChallengeIDSubmitPostOK1 sets APIV1ChallengeIDSubmitPostOK to APIV1ChallengeIDSubmitPostOK1.
func (s *APIV1ChallengeIDSubmitPostOK) SetAPIV1ChallengeIDSubmitPostOK1(v APIV1ChallengeIDSubmitPostOK1) {
	s.Type = APIV1ChallengeIDSubmitPostOK1APIV1ChallengeIDSubmitPostOK
	s.APIV1ChallengeIDSubmitPostOK1 = v
}

// GetAPIV1ChallengeIDSubmitPostOK1 returns APIV1ChallengeIDSubmitPostOK1 and true boolean if APIV1ChallengeIDSubmitPostOK is APIV1ChallengeIDSubmitPostOK1.
func (s APIV1ChallengeIDSubmitPostOK) GetAPIV1ChallengeIDSubmitPostOK1() (v APIV1ChallengeIDSubmitPostOK1, ok bool) {
	if !s.IsAPIV1ChallengeIDSubmitPostOK1() {
		return v, false
	}
	return s.APIV1ChallengeIDSubmitPostOK1, true
}

// NewAPIV1ChallengeIDSubmitPostOK1APIV1ChallengeIDSubmitPostOK returns new APIV1ChallengeIDSubmitPostOK from APIV1ChallengeIDSubmitPostOK1.
func NewAPIV1ChallengeIDSubmitPostOK1APIV1ChallengeIDSubmitPostOK(v APIV1ChallengeIDSubmitPostOK1) APIV1ChallengeIDSubmitPostOK {
	var s APIV1ChallengeIDSubmitPostOK
	s.SetAPIV1ChallengeIDSubmitPostOK1(v)
	return s
}

func (*APIV1ChallengeIDSubmitPostOK) aPIV1ChallengeIDSubmitPostRes() {}

type APIV1ChallengeIDSubmitPostOK0 struct {
	Valid OptBool `json:"valid"`
	Score OptInt  `json:"score"`
}

// GetValid returns the value of Valid.
func (s *APIV1ChallengeIDSubmitPostOK0) GetValid() OptBool {
	return s.Valid
}

// GetScore returns the value of Score.
func (s *APIV1ChallengeIDSubmitPostOK0) GetScore() OptInt {
	return s.Score
}

// SetValid sets the value of Valid.
func (s *APIV1ChallengeIDSubmitPostOK0) SetValid(val OptBool) {
	s.Valid = val
}

// SetScore sets the value of Score.
func (s *APIV1ChallengeIDSubmitPostOK0) SetScore(val OptInt) {
	s.Score = val
}

type APIV1ChallengeIDSubmitPostOK1 struct {
	Valid  OptBool   `json:"valid"`
	Reason OptString `json:"reason"`
}

// GetValid returns the value of Valid.
func (s *APIV1ChallengeIDSubmitPostOK1) GetValid() OptBool {
	return s.Valid
}

// GetReason returns the value of Reason.
func (s *APIV1ChallengeIDSubmitPostOK1) GetReason() OptString {
	return s.Reason
}

// SetValid sets the value of Valid.
func (s *APIV1ChallengeIDSubmitPostOK1) SetValid(val OptBool) {
	s.Valid = val
}

// SetReason sets the value of Reason.
func (s *APIV1ChallengeIDSubmitPostOK1) SetReason(val OptString) {
	s.Reason = val
}

type APIV1ChallengeIDSubmitPostReq struct {
	GunsPurchased []APIV1ChallengeIDSubmitPostReqGunsPurchasedItem `json:"gunsPurchased"`
	TotalCost     OptInt                                           `json:"totalCost"`
	Assignments   []APIV1ChallengeIDSubmitPostReqAssignmentsItem   `json:"assignments"`
}

// GetGunsPurchased returns the value of GunsPurchased.
func (s *APIV1ChallengeIDSubmitPostReq) GetGunsPurchased() []APIV1ChallengeIDSubmitPostReqGunsPurchasedItem {
	return s.GunsPurchased
}

// GetTotalCost returns the value of TotalCost.
func (s *APIV1ChallengeIDSubmitPostReq) GetTotalCost() OptInt {
	return s.TotalCost
}

// GetAssignments returns the value of Assignments.
func (s *APIV1ChallengeIDSubmitPostReq) GetAssignments() []APIV1ChallengeIDSubmitPostReqAssignmentsItem {
	return s.Assignments
}

// SetGunsPurchased sets the value of GunsPurchased.
func (s *APIV1ChallengeIDSubmitPostReq) SetGunsPurchased(val []APIV1ChallengeIDSubmitPostReqGunsPurchasedItem) {
	s.GunsPurchased = val
}

// SetTotalCost sets the value of TotalCost.
func (s *APIV1ChallengeIDSubmitPostReq) SetTotalCost(val OptInt) {
	s.TotalCost = val
}

// SetAssignments sets the value of Assignments.
func (s *APIV1ChallengeIDSubmitPostReq) SetAssignments(val []APIV1ChallengeIDSubmitPostReqAssignmentsItem) {
	s.Assignments = val
}

type APIV1ChallengeIDSubmitPostReqAssignmentsItem struct {
	Wave                    OptInt  `json:"wave"`
	GunQueues               [][]int `json:"gunQueues"`
	WallDurabilityRemaining OptInt  `json:"wallDurabilityRemaining"`
}

// GetWave returns the value of Wave.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) GetWave() OptInt {
	return s.Wave
}

// GetGunQueues returns the value of GunQueues.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) GetGunQueues() [][]int {
	return s.GunQueues
}

// GetWallDurabilityRemaining returns the value of WallDurabilityRemaining.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) GetWallDurabilityRemaining() OptInt {
	return s.WallDurabilityRemaining
}

// SetWave sets the value of Wave.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) SetWave(val OptInt) {
	s.Wave = val
}

// SetGunQueues sets the value of GunQueues.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) SetGunQueues(val [][]int) {
	s.GunQueues = val
}

// SetWallDurabilityRemaining sets the value of WallDurabilityRemaining.
func (s *APIV1ChallengeIDSubmitPostReqAssignmentsItem) SetWallDurabilityRemaining(val OptInt) {
	s.WallDurabilityRemaining = val
}

type APIV1ChallengeIDSubmitPostReqGunsPurchasedItem struct {
	Type OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType `json:"type"`
}

// GetType returns the value of Type.
func (s *APIV1ChallengeIDSubmitPostReqGunsPurchasedItem) GetType() OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType {
	return s.Type
}

// SetType sets the value of Type.
func (s *APIV1ChallengeIDSubmitPostReqGunsPurchasedItem) SetType(val OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) {
	s.Type = val
}

type APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType string

const (
	APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeTurret     APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType = "turret"
	APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeMachineGun APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType = "machineGun"
	APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeRayGun     APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType = "rayGun"
)

// AllValues returns all APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType values.
func (APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) AllValues() []APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType {
	return []APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType{
		APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeTurret,
		APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeMachineGun,
		APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeRayGun,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) MarshalText() ([]byte, error) {
	switch s {
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeTurret:
		return []byte(s), nil
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeMachineGun:
		return []byte(s), nil
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeRayGun:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) UnmarshalText(data []byte) error {
	switch APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType(data) {
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeTurret:
		*s = APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeTurret
		return nil
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeMachineGun:
		*s = APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeMachineGun
		return nil
	case APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeRayGun:
		*s = APIV1ChallengeIDSubmitPostReqGunsPurchasedItemTypeRayGun
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type APIV1MemberGetBadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1MemberGetBadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1MemberGetBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*APIV1MemberGetBadRequest) aPIV1MemberGetRes() {}

type APIV1MemberGetInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1MemberGetInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1MemberGetInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*APIV1MemberGetInternalServerError) aPIV1MemberGetRes() {}

// Unique identifier associated with the registered northeastern email.
type APIV1MemberGetOK struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIV1MemberGetOK) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIV1MemberGetOK) SetID(val uuid.UUID) {
	s.ID = val
}

func (*APIV1MemberGetOK) aPIV1MemberGetRes() {}

type APIV1MemberRegisterPostBadRequest struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1MemberRegisterPostBadRequest) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1MemberRegisterPostBadRequest) SetMessage(val string) {
	s.Message = val
}

func (*APIV1MemberRegisterPostBadRequest) aPIV1MemberRegisterPostRes() {}

type APIV1MemberRegisterPostConflict struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1MemberRegisterPostConflict) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1MemberRegisterPostConflict) SetMessage(val string) {
	s.Message = val
}

func (*APIV1MemberRegisterPostConflict) aPIV1MemberRegisterPostRes() {}

// Unique identifier associated with the registered northeastern email.
type APIV1MemberRegisterPostCreated struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *APIV1MemberRegisterPostCreated) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *APIV1MemberRegisterPostCreated) SetID(val uuid.UUID) {
	s.ID = val
}

func (*APIV1MemberRegisterPostCreated) aPIV1MemberRegisterPostRes() {}

type APIV1MemberRegisterPostInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *APIV1MemberRegisterPostInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *APIV1MemberRegisterPostInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*APIV1MemberRegisterPostInternalServerError) aPIV1MemberRegisterPostRes() {}

type APIV1MemberRegisterPostReq struct {
	// Must be a valid Northeastern email address.
	Email string `json:"email"`
	// Valid nuid.
	Nuid string `json:"nuid"`
}

// GetEmail returns the value of Email.
func (s *APIV1MemberRegisterPostReq) GetEmail() string {
	return s.Email
}

// GetNuid returns the value of Nuid.
func (s *APIV1MemberRegisterPostReq) GetNuid() string {
	return s.Nuid
}

// SetEmail sets the value of Email.
func (s *APIV1MemberRegisterPostReq) SetEmail(val string) {
	s.Email = val
}

// SetNuid sets the value of Nuid.
func (s *APIV1MemberRegisterPostReq) SetNuid(val string) {
	s.Nuid = val
}

type GetInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *GetInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *GetInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*GetInternalServerError) getRes() {}

type GetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetOK) getRes() {}

type HealthcheckGetInternalServerError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HealthcheckGetInternalServerError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HealthcheckGetInternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*HealthcheckGetInternalServerError) healthcheckGetRes() {}

type HealthcheckGetOK struct {
	Message OptHealthcheckGetOKMessage `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HealthcheckGetOK) GetMessage() OptHealthcheckGetOKMessage {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HealthcheckGetOK) SetMessage(val OptHealthcheckGetOKMessage) {
	s.Message = val
}

func (*HealthcheckGetOK) healthcheckGetRes() {}

type HealthcheckGetOKMessage string

const (
	HealthcheckGetOKMessageOK HealthcheckGetOKMessage = "OK"
)

// AllValues returns all HealthcheckGetOKMessage values.
func (HealthcheckGetOKMessage) AllValues() []HealthcheckGetOKMessage {
	return []HealthcheckGetOKMessage{
		HealthcheckGetOKMessageOK,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthcheckGetOKMessage) MarshalText() ([]byte, error) {
	switch s {
	case HealthcheckGetOKMessageOK:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthcheckGetOKMessage) UnmarshalText(data []byte) error {
	switch HealthcheckGetOKMessage(data) {
	case HealthcheckGetOKMessageOK:
		*s = HealthcheckGetOKMessageOK
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypes returns new OptAPIV1ChallengeIDAliensGetOKAlienTypes with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypes(v APIV1ChallengeIDAliensGetOKAlienTypes) OptAPIV1ChallengeIDAliensGetOKAlienTypes {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypes{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypes is optional APIV1ChallengeIDAliensGetOKAlienTypes.
type OptAPIV1ChallengeIDAliensGetOKAlienTypes struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypes
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypes was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypes) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypes) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypes
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypes) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypes) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypes) Get() (v APIV1ChallengeIDAliensGetOKAlienTypes, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypes) Or(d APIV1ChallengeIDAliensGetOKAlienTypes) APIV1ChallengeIDAliensGetOKAlienTypes {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBoss returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBoss(v APIV1ChallengeIDAliensGetOKAlienTypesBoss) OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss is optional APIV1ChallengeIDAliensGetOKAlienTypesBoss.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesBoss
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesBoss
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesBoss) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesBoss, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBoss) Or(d APIV1ChallengeIDAliensGetOKAlienTypesBoss) APIV1ChallengeIDAliensGetOKAlienTypesBoss {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk(v APIV1ChallengeIDAliensGetOKAlienTypesBossAtk) OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk is optional APIV1ChallengeIDAliensGetOKAlienTypesBossAtk.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesBossAtk
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesBossAtk
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesBossAtk) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesBossAtk, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossAtk) Or(d APIV1ChallengeIDAliensGetOKAlienTypesBossAtk) APIV1ChallengeIDAliensGetOKAlienTypesBossAtk {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp(v APIV1ChallengeIDAliensGetOKAlienTypesBossHp) OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp is optional APIV1ChallengeIDAliensGetOKAlienTypesBossHp.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesBossHp
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesBossHp
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesBossHp) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesBossHp, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossHp) Or(d APIV1ChallengeIDAliensGetOKAlienTypesBossHp) APIV1ChallengeIDAliensGetOKAlienTypesBossHp {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossID returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesBossID(v APIV1ChallengeIDAliensGetOKAlienTypesBossID) OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID is optional APIV1ChallengeIDAliensGetOKAlienTypesBossID.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesBossID
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesBossID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesBossID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesBossID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesBossID) Or(d APIV1ChallengeIDAliensGetOKAlienTypesBossID) APIV1ChallengeIDAliensGetOKAlienTypesBossID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegular returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegular(v APIV1ChallengeIDAliensGetOKAlienTypesRegular) OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular is optional APIV1ChallengeIDAliensGetOKAlienTypesRegular.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesRegular
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesRegular
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesRegular) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesRegular, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegular) Or(d APIV1ChallengeIDAliensGetOKAlienTypesRegular) APIV1ChallengeIDAliensGetOKAlienTypesRegular {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk(v APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk is optional APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) Or(d APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk) APIV1ChallengeIDAliensGetOKAlienTypesRegularAtk {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp(v APIV1ChallengeIDAliensGetOKAlienTypesRegularHp) OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp is optional APIV1ChallengeIDAliensGetOKAlienTypesRegularHp.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesRegularHp
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesRegularHp
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesRegularHp) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesRegularHp, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularHp) Or(d APIV1ChallengeIDAliensGetOKAlienTypesRegularHp) APIV1ChallengeIDAliensGetOKAlienTypesRegularHp {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID(v APIV1ChallengeIDAliensGetOKAlienTypesRegularID) OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID is optional APIV1ChallengeIDAliensGetOKAlienTypesRegularID.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesRegularID
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesRegularID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesRegularID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesRegularID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesRegularID) Or(d APIV1ChallengeIDAliensGetOKAlienTypesRegularID) APIV1ChallengeIDAliensGetOKAlienTypesRegularID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwift returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwift(v APIV1ChallengeIDAliensGetOKAlienTypesSwift) OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift is optional APIV1ChallengeIDAliensGetOKAlienTypesSwift.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesSwift
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesSwift
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesSwift) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesSwift, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwift) Or(d APIV1ChallengeIDAliensGetOKAlienTypesSwift) APIV1ChallengeIDAliensGetOKAlienTypesSwift {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk is optional APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) Or(d APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk) APIV1ChallengeIDAliensGetOKAlienTypesSwiftAtk {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp is optional APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) Or(d APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp) APIV1ChallengeIDAliensGetOKAlienTypesSwiftHp {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID returns new OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftID) OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID {
	return OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID is optional APIV1ChallengeIDAliensGetOKAlienTypesSwiftID.
type OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID struct {
	Value APIV1ChallengeIDAliensGetOKAlienTypesSwiftID
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) Reset() {
	var v APIV1ChallengeIDAliensGetOKAlienTypesSwiftID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) SetTo(v APIV1ChallengeIDAliensGetOKAlienTypesSwiftID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) Get() (v APIV1ChallengeIDAliensGetOKAlienTypesSwiftID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKAlienTypesSwiftID) Or(d APIV1ChallengeIDAliensGetOKAlienTypesSwiftID) APIV1ChallengeIDAliensGetOKAlienTypesSwiftID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKBudget returns new OptAPIV1ChallengeIDAliensGetOKBudget with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKBudget(v APIV1ChallengeIDAliensGetOKBudget) OptAPIV1ChallengeIDAliensGetOKBudget {
	return OptAPIV1ChallengeIDAliensGetOKBudget{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKBudget is optional APIV1ChallengeIDAliensGetOKBudget.
type OptAPIV1ChallengeIDAliensGetOKBudget struct {
	Value APIV1ChallengeIDAliensGetOKBudget
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKBudget was set.
func (o OptAPIV1ChallengeIDAliensGetOKBudget) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKBudget) Reset() {
	var v APIV1ChallengeIDAliensGetOKBudget
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKBudget) SetTo(v APIV1ChallengeIDAliensGetOKBudget) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKBudget) Get() (v APIV1ChallengeIDAliensGetOKBudget, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKBudget) Or(d APIV1ChallengeIDAliensGetOKBudget) APIV1ChallengeIDAliensGetOKBudget {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDAliensGetOKWallDurability returns new OptAPIV1ChallengeIDAliensGetOKWallDurability with value set to v.
func NewOptAPIV1ChallengeIDAliensGetOKWallDurability(v APIV1ChallengeIDAliensGetOKWallDurability) OptAPIV1ChallengeIDAliensGetOKWallDurability {
	return OptAPIV1ChallengeIDAliensGetOKWallDurability{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDAliensGetOKWallDurability is optional APIV1ChallengeIDAliensGetOKWallDurability.
type OptAPIV1ChallengeIDAliensGetOKWallDurability struct {
	Value APIV1ChallengeIDAliensGetOKWallDurability
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDAliensGetOKWallDurability was set.
func (o OptAPIV1ChallengeIDAliensGetOKWallDurability) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDAliensGetOKWallDurability) Reset() {
	var v APIV1ChallengeIDAliensGetOKWallDurability
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDAliensGetOKWallDurability) SetTo(v APIV1ChallengeIDAliensGetOKWallDurability) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDAliensGetOKWallDurability) Get() (v APIV1ChallengeIDAliensGetOKWallDurability, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDAliensGetOKWallDurability) Or(d APIV1ChallengeIDAliensGetOKWallDurability) APIV1ChallengeIDAliensGetOKWallDurability {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDSubmitPostReq returns new OptAPIV1ChallengeIDSubmitPostReq with value set to v.
func NewOptAPIV1ChallengeIDSubmitPostReq(v APIV1ChallengeIDSubmitPostReq) OptAPIV1ChallengeIDSubmitPostReq {
	return OptAPIV1ChallengeIDSubmitPostReq{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDSubmitPostReq is optional APIV1ChallengeIDSubmitPostReq.
type OptAPIV1ChallengeIDSubmitPostReq struct {
	Value APIV1ChallengeIDSubmitPostReq
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDSubmitPostReq was set.
func (o OptAPIV1ChallengeIDSubmitPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDSubmitPostReq) Reset() {
	var v APIV1ChallengeIDSubmitPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDSubmitPostReq) SetTo(v APIV1ChallengeIDSubmitPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDSubmitPostReq) Get() (v APIV1ChallengeIDSubmitPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDSubmitPostReq) Or(d APIV1ChallengeIDSubmitPostReq) APIV1ChallengeIDSubmitPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType returns new OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType with value set to v.
func NewOptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType(v APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType {
	return OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType is optional APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType.
type OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType struct {
	Value APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType
	Set   bool
}

// IsSet returns true if OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType was set.
func (o OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) Reset() {
	var v APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) SetTo(v APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) Get() (v APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) Or(d APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType) APIV1ChallengeIDSubmitPostReqGunsPurchasedItemType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAPIV1MemberRegisterPostReq returns new OptAPIV1MemberRegisterPostReq with value set to v.
func NewOptAPIV1MemberRegisterPostReq(v APIV1MemberRegisterPostReq) OptAPIV1MemberRegisterPostReq {
	return OptAPIV1MemberRegisterPostReq{
		Value: v,
		Set:   true,
	}
}

// OptAPIV1MemberRegisterPostReq is optional APIV1MemberRegisterPostReq.
type OptAPIV1MemberRegisterPostReq struct {
	Value APIV1MemberRegisterPostReq
	Set   bool
}

// IsSet returns true if OptAPIV1MemberRegisterPostReq was set.
func (o OptAPIV1MemberRegisterPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAPIV1MemberRegisterPostReq) Reset() {
	var v APIV1MemberRegisterPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAPIV1MemberRegisterPostReq) SetTo(v APIV1MemberRegisterPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAPIV1MemberRegisterPostReq) Get() (v APIV1MemberRegisterPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAPIV1MemberRegisterPostReq) Or(d APIV1MemberRegisterPostReq) APIV1MemberRegisterPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptHealthcheckGetOKMessage returns new OptHealthcheckGetOKMessage with value set to v.
func NewOptHealthcheckGetOKMessage(v HealthcheckGetOKMessage) OptHealthcheckGetOKMessage {
	return OptHealthcheckGetOKMessage{
		Value: v,
		Set:   true,
	}
}

// OptHealthcheckGetOKMessage is optional HealthcheckGetOKMessage.
type OptHealthcheckGetOKMessage struct {
	Value HealthcheckGetOKMessage
	Set   bool
}

// IsSet returns true if OptHealthcheckGetOKMessage was set.
func (o OptHealthcheckGetOKMessage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptHealthcheckGetOKMessage) Reset() {
	var v HealthcheckGetOKMessage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptHealthcheckGetOKMessage) SetTo(v HealthcheckGetOKMessage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptHealthcheckGetOKMessage) Get() (v HealthcheckGetOKMessage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptHealthcheckGetOKMessage) Or(d HealthcheckGetOKMessage) HealthcheckGetOKMessage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
