// Code generated by ogen, DO NOT EDIT.
package api

type APIV1ChallengeBackendIDAliensGetRes interface {
	aPIV1ChallengeBackendIDAliensGetRes()
}

type APIV1ChallengeBackendIDAliensSubmitPostRes interface {
	aPIV1ChallengeBackendIDAliensSubmitPostRes()
}

type APIV1MemberGetRes interface {
	aPIV1MemberGetRes()
}

type APIV1MemberRegisterPostRes interface {
	aPIV1MemberRegisterPostRes()
}

type GetRes interface {
	getRes()
}
