// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1RegisterGet implements GET /api/v1/register operation.
//
// GET /api/v1/register
func (UnimplementedHandler) APIV1RegisterGet(ctx context.Context, req OptAPIV1RegisterGetReq) (r *APIV1RegisterGetCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// Get implements GET / operation.
//
// API documentation.
//
// GET /
func (UnimplementedHandler) Get(ctx context.Context) (r GetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthcheckGet implements GET /healthcheck operation.
//
// GET /healthcheck
func (UnimplementedHandler) HealthcheckGet(ctx context.Context) (r *HealthcheckGetOK, _ error) {
	return r, ht.ErrNotImplemented
}
