# https://taskfile.dev
---
version: "3"

dotenv: ["./.env.test"]

includes:
  challenge:
    taskfile: ./challenge/Taskfile.yml
    dir: ./challenge
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

tasks:
  docker-build:
    deps:
      - sync
    summary: Build the docker image for the challenge server for deployment
    cmds:
      - docker build --platform linux/amd64 -t generate_technical_2025-challenge:latest -f challenge.Dockerfile .
  docker-save:
    deps:
      - docker-build
    summary: Saves the docker image to a file on disk (Useful for manual uploads.)
    cmds:
      - docker save generate_technical_2025-challenge:latest | gzip > challenge.tar.gz
  docker-develop-run:
    deps:
      - sync
    summary: Run development db and server in docker.
    cmds:
      - docker rmi -f generate_technical_2025-challenge:latest
      - docker compose down --volumes
      - docker compose up --watch
  sync:
    summary: Syncs up both generate api schema and server code.
    cmds:
      - task api:generate
      - task challenge:generate
