# https://taskfile.dev
---
version: "3"

dotenv: ["./.env.test"]

includes:
  challenge:
    taskfile: ./challenge/Taskfile.yml
    dir: ./challenge
  api:
    taskfile: ./api/Taskfile.yml
    dir: ./api

tasks:
  docker-develop-run:
    deps:
      - sync
    summary: Run development db and server in docker.
    cmds:
      - docker rmi -f generate_technical_2025-challenge:latest
      - docker compose down --volumes
      - docker compose up --watch
  sync:
    summary: Syncs up both generate api schema and server code.
    cmds:
      - task api:generate
      - task challenge:generate
